#!/bin/zsh

trap "trap - TERM && kill -- -$$" INT TERM EXIT

watchexec -e ts,md --timings -c=clear -- "tsc" &

if [[ "$1" == "host" ]]; then
    echo "Hosting files"
    (cd PolyModLoader; python ../httpserver.py 8000 &> /dev/null) &
    python httpserver.py 8001 &> /dev/null &
fi

wait
